### ISSUE TITLE
Model subscribe not handle changes in model on creating a new model object from views or shell.

### ISSUE THREAD

**Issue by Dr4g0s** [LostMoa/djangochannelsrestframework#57]
**Describe the bug**
Model subscribe not handle changes in model on creating a new model object from views or shell it only works from admin panel

Consumer code :
```
class LiveNotificationConsumer(ListModelMixin, GenericAsyncAPIConsumer):
    serializer_class = NotificationSerializer
    permission_classes = (permissions.IsAuthenticated,)

    async def accept(self, **kwargs):
        await super().accept(** kwargs)
        await self.model_change.subscribe()

    @model_observer(Notification)
    async def model_change(self, message, action=None, **kwargs):
        if message['user'] == self.scope['user'].id:
            await self.send_json(message)

    @model_change.serializer
    def model_serialize(self, instance, action, **kwargs):
        return NotificationSerializer(instance).data

    def get_queryset(self, *args, **kwargs):
        user = self.scope['user']
        return user.notifications.all()
```

Client code :
```
var endpoint = "ws://127.0.0.1:8000/ws/notifications/"
        var ws = new WebSocket(endpoint + "?token=" + token)
        ws.onmessage = function(e){
            console.log('comming data -->', e.data)
        }

        var msg = JSON.stringify({
            action: "list",
            request_id: 6,
        })
        ws.onopen = () =>  ws.send(msg);

        ws.onclose = function (e) {
            console.log(e)
            console.error('Error websocket');
        };
```

 - OS: [Ubuntu]
 - Version [12.04]

**Comment by hishnash** [comment]
How are you running your server?

**Comment by Dr4g0s** [comment]
I'm running django local server & production(nginx,daphne,gunicorn),
i tried to use signals in my project but it's also doesn't work from shell or external function just admin panel,
also this is my function 
```
async def send_notification_to_all(data, users=None):
    if not users:
        users = User.objects.values_list('id', flat=True)

    Notification.objects.bulk_create(
        [Notification(
            user_id=user, title=data['title'], message=data['message'], url=data['url']
            ) for user in users
        ]
    )

asyncio.run(send_notification_to_all(data))
```

**Comment by Dr4g0s** [comment]
After searching alot i sloved the problem i found that bulk_create not working with signals, thanks @hishnash .

**Comment by Dr4g0s** [comment]
Hi @hishnash could you help me please i have another problem when using celery with djangochannelsrestframework,
model_observer not handle changes on celery async tasks 
```
@shared_task
def send_notification_to_all(data, users=None):
    if not users:
        users = User.objects.values_list('id', flat=True)
    for user in users[]:
        Notification.objects.using('notifications').create(
                            user_id=user, title=data['title'], 
                                message=data['message'], url=data['url'])

send_notification_to_all.apply_async([data])
```
all result saved to database but model_observer can't handle anything.

**Comment by hishnash** [comment]
when running celery workers are the consumer files imported?

**Comment by Dr4g0s** [comment]
how to ensure that these files imported ?

**Comment by hishnash** [comment]
I suggest adding an import statement to you consumers file in your `__init__.py` in the App folder.

**Comment by hishnash** [comment]
```
- proj/
  - manage.py
  - myapp/
    - __init__.py
    - settings.py
    - urls.py
    - consumers.py
```

Add a `import consumers` to the `__init__.py`

**Comment by Dr4g0s** [comment]
It raise exception `django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet`

**Comment by Dr4g0s** [comment]
Thanks @hishnash it's finally worked for me when by adding consumers file in apps.py file.

**Comment by hishnash** [comment]
Good to know I should add this to the documentation.

**Comment by hishnash** [comment]
I also want to find a good way to support bulk updates, at least some way that you can manually advice the consumer things have changed.. do you have any ideas on what might be a good api for this?

**Comment by Dr4g0s** [comment]
Thanks for your efforts, unfortunately i don't know i'm new on channels.

**Comment by lautarodapin** [comment]
> I also want to find a good way to support bulk updates, at least some way that you can manually advice the consumer things have changed.. do you have any ideas on what might be a good api for this?

I'm investigating a little bit about this issue.
I saw [this post](https://stackoverflow.com/questions/30632743/how-can-i-use-signals-in-django-bulk-create) where a partial solution can be applied.

Maybe worth trying out

**Comment by W0rtX** [comment]
> Thanks @hishnash it's finally worked for me when by adding consumers file in apps.py file.

Hello, can you make small example?

**Comment by W0rtX** [comment]
> Good to know I should add this to the documentation.

Please tell me, was this added to the documentation?
